version: 0.0
os: linux

files:
  - source:  /
    destination: /home/ubuntu/Flower_back
    overwrite: yes

permissions:
  - object: /
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: stop.sh
      timeout: 60
  ApplicationStart:
    - location: start.sh
      timeout: 60
